<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="C:\Lattice\Lattice.csproj"/>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Lattice.Sandbox</RootNamespace>
    <AssemblyName>Lattice.Sandbox</AssemblyName>
    <TargetFramework>net48</TargetFramework>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
